microscope:
  name: PPM
  type: UprightBrightfield
  detector_in_use: null
  objective_in_use: null
  modality: null
test-push:
  MSN: PPM_001
modalities:
  ppm:
    type: polarized
    optics: 1
    pizstage_offset: 177082.5
    rotation_stage:
      device: LOCI_STAGE_PI_001
      type: polarizer
    rotation_angles:
    - name: negative
      tick: -7
    - name: crossed
      tick: 0
    - name: positive
      tick: 7
    - name: uncrossed
      tick: 90
  brightfield:
    type: brightfield
hardware:
  objectives:
  - id: LOCI_OBJECTIVE_OLYMPUS_10X_001
    pixel_size_xy_um:
      LOCI_DETECTOR_TELEDYNE_001: 0.4537
      LOCI_DETECTOR_JAI_001: 0.347
    pixel_size_z_um: null
  - id: LOCI_OBJECTIVE_OLYMPUS_20X_POL_001
    pixel_size_xy_um:
      LOCI_DETECTOR_TELEDYNE_001: 0.2271
      LOCI_DETECTOR_JAI_001: 0.1725
    pixel_size_z_um: null
  - id: LOCI_OBJECTIVE_OLYMPUS_40X_POL_001
    pixel_size_xy_um:
      LOCI_DETECTOR_TELEDYNE_001: 0.1142
      LOCI_DETECTOR_JAI_001: 0.0871
    pixel_size_z_um: null
  detectors:
  - LOCI_DETECTOR_TELEDYNE_001
  - LOCI_DETECTOR_JAI_001
stage:
  stage_id: LOCI_STAGE_PRIOR_001
  limits:
    x_um:
      low: -36000
      high: 35500
    y_um:
      low: -39000
      high: 34000
    z_um:
      low: -100
      high: 1000
  inserts:
    slide_margin_um: 2000
    default: single_h
    configurations:
      single_h:
        name: Single Slide (Horizontal)
        description: Standard single slide holder with horizontal orientation
        aperture_left_x_um: 34873
        aperture_right_x_um: -35085
        aperture_top_y_um: 23007
        aperture_bottom_y_um: -48114
        slide_left_x_um: 35400
        slide_right_x_um: -40000
        slide_top_y_um: 4807
        slide_bottom_y_um: -23241
        aperture_height_mm: 60.0
        slide_width_mm: 75
        slide_height_mm: 25
      single_v:
        name: Single Slide (Vertical)
        description: Standard single slide holder with vertical orientation
        aperture_left_x_um: 0
        aperture_right_x_um: 60000
        slide_top_y_um: 0
        slide_bottom_y_um: 75000
        aperture_height_mm: 55.0
        slide_width_mm: 25
        slide_height_mm: 75
      quad_v:
        name: Four Slides (Vertical)
        description: Four slides arranged vertically
        aperture_left_x_um: 0
        aperture_right_x_um: 120000
        slide_top_y_um: 0
        slide_bottom_y_um: 75000
        aperture_height_mm: 55.0
        slide_width_mm: 25
        slide_height_mm: 75
        slide_spacing_mm: 30.0
        num_slides: 4
  streaming_af:
    enabled: true
    speed_property: MaxSpeed
    slow_speed_value: '1'
    slow_speed_um_per_s: 1.422
    normal_speed_value: '100'
slide_size_um:
  x: 40000
  y: 20000
